name: Pull request checks

on: pull_request

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    code-checks:
        name: Run code checks and quality tools
        uses: ./.github/workflows/code-checker.yml
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
